# Dependencies
markdown: kramdown
highlighter: rouge

# Permalinks
permalink:        pretty

# Setup
title:            Manish Devgan
tagline:          'Coding Experiences'
description:      'I post what I did & sometimes what I learned'
baseurl:          /

author:
  name:           'Manish Devgan'
  url:            https://github.com/gabru-md

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/gabru-md/gabru-md.github.io
